package auth

import (
	"crypto/rand"
	"encoding/json"
	"fmt"
	"math/big"
	"os"
	"strings"

	"golang.org/x/crypto/bcrypt"
)

const (
	AuthDir       = "/etc/mitte/auth"
	ConfigFile    = AuthDir + "/configuration.yml"
	UsersFile     = AuthDir + "/users_database.yml"
	DataDir       = AuthDir + "/data"
	AutheliaImage = "authelia/authelia:latest"
	AutheliaPort  = "9091"
	ContainerName = "mitte-authelia"
)

// Config holds the Authelia configuration parameters.
type Config struct {
	JWTSecret     string
	SessionSecret string
	EncryptionKey string
	BaseDomain    string
	AutheliaURL   string // e.g. https://auth.example.com
	CookieDomain  string // e.g. .example.com
}

// EnsureAuthDir creates the auth config directory structure.
func EnsureAuthDir() error {
	if err := os.MkdirAll(AuthDir, 0755); err != nil {
		return fmt.Errorf("failed to create auth directory: %w", err)
	}
	if err := os.MkdirAll(DataDir, 0755); err != nil {
		return fmt.Errorf("failed to create auth data directory: %w", err)
	}
	return nil
}

// IsSetup returns true if Authelia has been configured.
func IsSetup() bool {
	_, err := os.Stat(ConfigFile)
	return err == nil
}

// GenerateConfig creates the Authelia configuration YAML.
func GenerateConfig(cfg Config) error {
	if err := EnsureAuthDir(); err != nil {
		return err
	}

	content := fmt.Sprintf(`# Mitte Authelia Configuration
# Generated by mitte auth setup — do not edit manually.

theme: auto

server:
  address: tcp://0.0.0.0:9091/

log:
  level: info

jwt_secret: %s

authentication_backend:
  file:
    path: /config/users_database.yml
    password:
      algorithm: argon2id
      argon2:
        variant: argon2id
        iterations: 3
        memory: 65536
        parallelism: 4
        key_length: 32
        salt_length: 16

session:
  name: mitte_auth_session
  secret: %s
  expiration: 3600
  inactivity: 300
  cookies:
    - domain: %s
      authelia_url: %s

storage:
  encryption_key: %s
  local:
    path: /config/db.sqlite3

access_control:
  default_policy: one_factor

notifier:
  filesystem:
    filename: /config/notification.txt
`, cfg.JWTSecret, cfg.SessionSecret, cfg.CookieDomain, cfg.AutheliaURL, cfg.EncryptionKey)

	if err := os.WriteFile(ConfigFile, []byte(content), 0644); err != nil {
		return fmt.Errorf("failed to write Authelia config: %w", err)
	}

	return nil
}

// GenerateUsersFile creates an empty users database file.
func GenerateUsersFile() error {
	if err := EnsureAuthDir(); err != nil {
		return err
	}

	content := `# Mitte Authelia Users Database
# Generated by mitte auth setup.
#
# Use 'mitte auth add-user <username>' to add users.
#
# Passwords are hashed with argon2id.
# Do not edit this file manually unless you know what you are doing.

users:
`
	if err := os.WriteFile(UsersFile, []byte(content), 0644); err != nil {
		return fmt.Errorf("failed to write users file: %w", err)
	}
	return nil
}

// UserEntry represents a user in the Authelia users database.
type UserEntry struct {
	Username    string
	DisplayName string
	Email       string
	Password    string // bcrypt hash
	Groups      []string
}

// AddUser adds a new user to the Authelia users database.
// The password should be provided in plain text; it will be hashed.
func AddUser(entry UserEntry, password string) error {
	if !IsSetup() {
		return fmt.Errorf("auth not configured. Run 'mitte auth setup' first")
	}

	hash, err := hashPassword(password)
	if err != nil {
		return fmt.Errorf("failed to hash password: %w", err)
	}

	// Read existing users file
	data, err := os.ReadFile(UsersFile)
	if err != nil {
		return fmt.Errorf("failed to read users file: %w", err)
	}

	// Check if user already exists
	if strings.Contains(string(data), fmt.Sprintf("  %s:", entry.Username)) {
		return fmt.Errorf("user '%s' already exists", entry.Username)
	}

	groups := strings.Join(entry.Groups, ", ")
	if groups == "" {
		groups = "users"
	}

	userBlock := fmt.Sprintf(`  %s:
    disabled: false
    displayname: "%s"
    password: "%s"
    email: %s
    groups:
      - %s
`, entry.Username, entry.DisplayName, hash, entry.Email, strings.Join(entry.Groups, "\n      - "))

	// Append to file
	f, err := os.OpenFile(UsersFile, os.O_APPEND|os.O_WRONLY, 0644)
	if err != nil {
		return fmt.Errorf("failed to open users file: %w", err)
	}
	defer f.Close()

	if _, err := f.WriteString(userBlock); err != nil {
		return fmt.Errorf("failed to write user entry: %w", err)
	}

	return nil
}

// RemoveUser removes a user from the Authelia users database.
func RemoveUser(username string) error {
	if !IsSetup() {
		return fmt.Errorf("auth not configured. Run 'mitte auth setup' first")
	}

	data, err := os.ReadFile(UsersFile)
	if err != nil {
		return fmt.Errorf("failed to read users file: %w", err)
	}

	lines := strings.Split(string(data), "\n")
	var result []string
	skip := false

	for _, line := range lines {
		trimmed := strings.TrimSpace(line)

		// Detect start of user block to remove
		if strings.HasPrefix(line, fmt.Sprintf("  %s:", username)) {
			skip = true
			continue
		}

		// Detect start of next user block (or non-indented line) to stop skipping
		if skip {
			if strings.HasPrefix(line, "  ") && !strings.HasPrefix(trimmed, "-") && strings.HasSuffix(trimmed, ":") && !strings.Contains(trimmed, " ") {
				skip = false
			} else if !strings.HasPrefix(line, "  ") && trimmed != "" {
				skip = false
			}
		}

		if !skip {
			result = append(result, line)
		}
	}

	if err := os.WriteFile(UsersFile, []byte(strings.Join(result, "\n")), 0644); err != nil {
		return fmt.Errorf("failed to write users file: %w", err)
	}

	return nil
}

// ListUsers parses the users database and returns user entries.
func ListUsers() ([]UserEntry, error) {
	if !IsSetup() {
		return nil, fmt.Errorf("auth not configured. Run 'mitte auth setup' first")
	}

	data, err := os.ReadFile(UsersFile)
	if err != nil {
		return nil, fmt.Errorf("failed to read users file: %w", err)
	}

	var users []UserEntry
	var current *UserEntry

	for _, line := range strings.Split(string(data), "\n") {
		trimmed := strings.TrimSpace(line)

		// User line: "  username:" (2 spaces indent, ends with colon, no spaces in the middle)
		if strings.HasPrefix(line, "  ") && strings.HasSuffix(trimmed, ":") && !strings.Contains(trimmed, " ") && len(trimmed) > 1 {
			if current != nil {
				users = append(users, *current)
			}
			username := strings.TrimSuffix(trimmed, ":")
			current = &UserEntry{Username: username}
			continue
		}

		if current == nil {
			continue
		}

		// Parse fields
		if strings.HasPrefix(trimmed, "displayname:") {
			current.DisplayName = strings.Trim(strings.TrimPrefix(trimmed, "displayname:"), ` "`)
		} else if strings.HasPrefix(trimmed, "email:") {
			current.Email = strings.TrimSpace(strings.TrimPrefix(trimmed, "email:"))
		} else if strings.HasPrefix(trimmed, "password:") {
			current.Password = strings.Trim(strings.TrimPrefix(trimmed, "password:"), ` "`)
		} else if strings.HasPrefix(trimmed, "- ") {
			current.Groups = append(current.Groups, strings.TrimPrefix(trimmed, "- "))
		}
	}

	if current != nil {
		users = append(users, *current)
	}

	return users, nil
}

// GenerateSecret generates a random secret string.
func GenerateSecret(length int) (string, error) {
	const chars = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789"
	result := make([]byte, length)
	for i := range result {
		idx, err := rand.Int(rand.Reader, big.NewInt(int64(len(chars))))
		if err != nil {
			return "", err
		}
		result[i] = chars[idx.Int64()]
	}
	return string(result), nil
}

// hashPassword hashes a password using bcrypt.
func hashPassword(password string) (string, error) {
	hash, err := bcrypt.GenerateFromPassword([]byte(password), bcrypt.DefaultCost)
	if err != nil {
		return "", err
	}
	return string(hash), nil
}

// ConfigDir returns the auth config directory.
func ConfigDir() string {
	return AuthDir
}

// LoginPortalURL returns the URL for the auth login portal.
func LoginPortalURL(baseDomain string) string {
	return fmt.Sprintf("https://auth.%s", baseDomain)
}

// CookieDomain returns the cookie domain for the given base domain.
func CookieDomain(baseDomain string) string {
	return fmt.Sprintf(".%s", baseDomain)
}

// ACLRule represents a per-domain access control rule.
type ACLRule struct {
	Domain string
	Policy string // "one_factor" or "two_factor"
}

// GenerateConfigWithACL creates the Authelia configuration YAML with ACL rules.
func GenerateConfigWithACL(cfg Config, rules []ACLRule) error {
	if err := EnsureAuthDir(); err != nil {
		return err
	}

	var rulesYAML strings.Builder
	for _, rule := range rules {
		rulesYAML.WriteString(fmt.Sprintf("    - domain: %s\n      policy: %s\n", rule.Domain, rule.Policy))
	}

	content := fmt.Sprintf(`# Mitte Authelia Configuration
# Generated by mitte auth — do not edit manually.

theme: auto

server:
  address: tcp://0.0.0.0:9091/

log:
  level: info

jwt_secret: %s

authentication_backend:
  file:
    path: /config/users_database.yml
    password:
      algorithm: argon2id
      argon2:
        variant: argon2id
        iterations: 3
        memory: 65536
        parallelism: 4
        key_length: 32
        salt_length: 16

session:
  name: mitte_auth_session
  secret: %s
  expiration: 3600
  inactivity: 300
  cookies:
    - domain: %s
      authelia_url: %s

storage:
  encryption_key: %s
  local:
    path: /config/db.sqlite3

access_control:
  default_policy: one_factor
  rules:
%s
notifier:
  filesystem:
    filename: /config/notification.txt
`, cfg.JWTSecret, cfg.SessionSecret, cfg.CookieDomain, cfg.AutheliaURL, cfg.EncryptionKey, rulesYAML.String())

	if err := os.WriteFile(ConfigFile, []byte(content), 0644); err != nil {
		return fmt.Errorf("failed to write Authelia config: %w", err)
	}

	return nil
}

// LoadConfig reads the existing Authelia config and extracts secrets.
func LoadConfig() (*Config, error) {
	if !IsSetup() {
		return nil, fmt.Errorf("auth not configured. Run 'mitte auth setup' first")
	}

	data, err := os.ReadFile(ConfigFile)
	if err != nil {
		return nil, fmt.Errorf("failed to read config: %w", err)
	}

	content := string(data)

	cfg := &Config{}

	// Extract secrets by parsing lines
	for _, line := range strings.Split(content, "\n") {
		trimmed := strings.TrimSpace(line)
		if strings.HasPrefix(trimmed, "jwt_secret:") {
			cfg.JWTSecret = strings.TrimSpace(strings.TrimPrefix(trimmed, "jwt_secret:"))
		} else if strings.HasPrefix(trimmed, "secret:") && cfg.SessionSecret == "" {
			cfg.SessionSecret = strings.TrimSpace(strings.TrimPrefix(trimmed, "secret:"))
		} else if strings.HasPrefix(trimmed, "encryption_key:") {
			cfg.EncryptionKey = strings.TrimSpace(strings.TrimPrefix(trimmed, "encryption_key:"))
		} else if strings.HasPrefix(trimmed, "- domain:") {
			// First domain in cookies is our cookie domain
			if cfg.CookieDomain == "" {
				cfg.CookieDomain = strings.TrimSpace(strings.TrimPrefix(trimmed, "- domain:"))
			}
		} else if strings.HasPrefix(trimmed, "authelia_url:") {
			cfg.AutheliaURL = strings.TrimSpace(strings.TrimPrefix(trimmed, "authelia_url:"))
		}
	}

	return cfg, nil
}

// CollectACLRules scans all app state files and returns ACL rules for protected apps.
func CollectACLRules() ([]ACLRule, error) {
	const appsDir = "/var/lib/mitte/apps"

	entries, err := os.ReadDir(appsDir)
	if err != nil {
		if os.IsNotExist(err) {
			return nil, nil
		}
		return nil, fmt.Errorf("failed to read apps directory: %w", err)
	}

	var rules []ACLRule
	for _, entry := range entries {
		if entry.IsDir() || !strings.HasSuffix(entry.Name(), ".json") {
			continue
		}

		data, err := os.ReadFile(appsDir + "/" + entry.Name())
		if err != nil {
			continue
		}

		// Minimal parsing to extract auth config and domains
		app, err := parseAppForACL(string(data))
		if err != nil || app == nil || app.Auth == nil || !app.Auth.Enabled {
			continue
		}

		for _, domain := range app.Domains {
			rules = append(rules, ACLRule{
				Domain: domain,
				Policy: app.Auth.Policy,
			})
		}
	}

	return rules, nil
}

// miniApp is a minimal struct for parsing app JSON for ACL rules.
type miniApp struct {
	Domains []string `json:"domains"`
	Auth    *struct {
		Enabled bool   `json:"enabled"`
		Policy  string `json:"policy"`
	} `json:"auth,omitempty"`
}

func parseAppForACL(jsonStr string) (*miniApp, error) {
	var app miniApp
	if err := jsonUnmarshalMinimal(jsonStr, &app); err != nil {
		return nil, err
	}
	return &app, nil
}

// jsonUnmarshalMinimal is a simple JSON parser for our miniApp struct.
func jsonUnmarshalMinimal(data string, app *miniApp) error {
	// Use encoding/json
	type alias miniApp
	var a alias
	if err := json.Unmarshal([]byte(data), &a); err != nil {
		return err
	}
	*app = miniApp(a)
	return nil
}
